### PR TITLE
remove log from html output

### PR DESCRIPTION
**Pull request by svennd**
logfile is great for svennd/NanoPlotdebugging, not so much for the html report; I would strip it from the html output.

### CODE REVIEW

**Comment by wdecoster** [comment]
Perhaps we could make inclusion of the log optional? However, don't want to add too much flags.  I agree it's not too pretty. Or hide it on a separate page. Something to take into account for sure.

**Comment by svennd** [comment]
no a flag would be a bit overkill, its content is debugging, so text format is fine, I don't see the advantage of including it in a html/pdf report.

**Comment by wdecoster** [comment]
Hm yes you're right. Merged ;)

**Comment by wdecoster** [comment]
Will push to PyPI later.

**Pull request merged**
