### PR TITLE
--only-report option added

### PR DESCRIPTION
**Pull request by juanjo255**
Hello wdecoster,

I added the option to return only the report.html and the nanostats.txt 

Thanks for this tool btw!

PS: I've used a lot NanoPack, I love it. I'm last year undergrad and this feels goooood, I hope it works for you :)

Juan

### CODE REVIEW

**Comment by wdecoster** [comment]
Hi,

Thank you! I am a little confused about the location you picked for changing the Plot class, under the `else` part of `if args.barcoded:`. This would mean that the --only-report flag doesn't do anything when you are running with `--barcoded`. Was that intentional?

Wouter

**Comment by juanjo255** [comment]
Yes, it was. I,ve never used barcodes so I didn't want to mess up.

**Comment by wdecoster** [comment]
Should be fine :)

**Comment by wdecoster** [comment]
Looks good! I will assume you tested this?

**Comment by juanjo255** [comment]
Not for barcoded, but for the other one :)

**Comment by wdecoster** [comment]
Great, thanks again!

**Pull request merged**
